#!/usr/bin/env python3
"""Generate probe_facts.json with 100 probe facts (40 explicit, 35 grounded, 25 implicit)."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "probes" / "probe_facts.json"

facts = []

# ── TYPE 1: EXPLICIT RECALL (PF-001 to PF-040) ────────────────────────────────

EXPLICIT = [
    # Software Engineering
    ("PF-001","The internal ticket for the authentication regression is BUG-4471 and it was assigned to engineer Priya Nair.",
     [("What is the bug ticket number for the authentication regression?","BUG-4471","exact_match"),
      ("Who was assigned bug ticket BUG-4471?","Priya Nair","exact_match"),
      ("Which engineer is responsible for the authentication regression fix?","Priya Nair","exact_match"),
      ("What kind of issue is BUG-4471?","authentication regression","exact_match"),
      ("Name the ticket ID for the authentication issue assigned to Priya Nair.","BUG-4471","exact_match")]),
    ("PF-002","The staging deployment URL is https://staging.intl-api.corp/v3 and the environment token is ENV-STAGE-88F.",
     [("What is the staging deployment URL?","https://staging.intl-api.corp/v3","exact_match"),
      ("What is the environment token for staging?","ENV-STAGE-88F","exact_match"),
      ("Which token is used for the staging environment?","ENV-STAGE-88F","exact_match"),
      ("What path version is in the staging URL?","v3","exact_match"),
      ("Give the full staging URL including version.","https://staging.intl-api.corp/v3","exact_match")]),
    ("PF-003","The CI/CD pipeline for the payments-service runs on runner node CI-NODE-17 with a timeout of 45 minutes.",
     [("Which runner node handles the payments-service CI/CD pipeline?","CI-NODE-17","exact_match"),
      ("What is the timeout for the payments-service pipeline?","45 minutes","exact_match"),
      ("How long before the payments-service CI job times out?","45 minutes","exact_match"),
      ("What is the CI node ID for payments-service?","CI-NODE-17","exact_match"),
      ("State the runner node and timeout for payments-service.","CI-NODE-17 with a timeout of 45 minutes","exact_match")]),
    ("PF-004","Repository prism-core is pinned to commit hash a3d9f21 for the Q2 release freeze.",
     [("What commit hash is prism-core pinned to for the Q2 release?","a3d9f21","exact_match"),
      ("Which release freeze applies to commit a3d9f21 in prism-core?","Q2","exact_match"),
      ("Name the repository pinned to commit a3d9f21.","prism-core","exact_match"),
      ("What is the frozen commit for prism-core during Q2?","a3d9f21","exact_match"),
      ("During which release freeze is prism-core at commit a3d9f21?","Q2 release freeze","exact_match")]),
    ("PF-005","The API rate limit for the /search endpoint is 120 requests per minute per client token.",
     [("What is the rate limit for the /search endpoint?","120 requests per minute","exact_match"),
      ("How many requests per minute are allowed on /search per client?","120","exact_match"),
      ("Per what unit are /search rate limits applied?","per client token","exact_match"),
      ("What is the per-token RPM cap for /search?","120","exact_match"),
      ("State the complete rate limit rule for /search.","120 requests per minute per client token","exact_match")]),
    # Biomedical
    ("PF-006","Clinical trial NCT-2024-0078 enrolled 312 participants in the Phase II cohort, stratified by age group 45–65.",
     [("What is the trial ID for the Phase II study with 312 participants?","NCT-2024-0078","exact_match"),
      ("How many participants were enrolled in trial NCT-2024-0078?","312","exact_match"),
      ("What age group was the stratification criterion for NCT-2024-0078?","45–65","exact_match"),
      ("Which trial phase is NCT-2024-0078?","Phase II","exact_match"),
      ("Give the cohort size for trial NCT-2024-0078.","312","exact_match")]),
    ("PF-007","The investigational drug compound is designated IDP-5533 and its maximum tolerated dose established in Phase I was 80 mg/kg.",
     [("What is the designation for the investigational drug?","IDP-5533","exact_match"),
      ("What is the maximum tolerated dose of IDP-5533?","80 mg/kg","exact_match"),
      ("In which phase was the MTD of IDP-5533 established?","Phase I","exact_match"),
      ("State the MTD for compound IDP-5533.","80 mg/kg","exact_match"),
      ("What compound has a Phase I MTD of 80 mg/kg?","IDP-5533","exact_match")]),
    ("PF-008","The primary endpoint measurement interval is 16 weeks and the secondary endpoint interval is 32 weeks for study BMS-RCT-9.",
     [("What is the primary endpoint interval for BMS-RCT-9?","16 weeks","exact_match"),
      ("What is the secondary endpoint interval for BMS-RCT-9?","32 weeks","exact_match"),
      ("Which study has a 16-week primary and 32-week secondary endpoint?","BMS-RCT-9","exact_match"),
      ("How long is the secondary follow-up in BMS-RCT-9?","32 weeks","exact_match"),
      ("Name the study whose primary endpoint is at 16 weeks.","BMS-RCT-9","exact_match")]),
    # Legal / Compliance
    ("PF-009","Contract clause 14.3(b) mandates a 30-day written notice period before any service termination.",
     [("What notice period is required under clause 14.3(b)?","30 days","exact_match"),
      ("Which contract clause governs service termination notice?","14.3(b)","exact_match"),
      ("What form must the notice under clause 14.3(b) take?","written","exact_match"),
      ("How many days' notice does clause 14.3(b) require?","30","exact_match"),
      ("State the termination notice requirement from clause 14.3(b).","30-day written notice","exact_match")]),
    ("PF-010","The GDPR compliance audit reference is AUDIT-EU-2025-441 and the next review is scheduled for September 14, 2026.",
     [("What is the GDPR audit reference number?","AUDIT-EU-2025-441","exact_match"),
      ("When is the next review for AUDIT-EU-2025-441?","September 14, 2026","exact_match"),
      ("Which regulation does AUDIT-EU-2025-441 cover?","GDPR","exact_match"),
      ("Give the review date for the GDPR compliance audit.","September 14, 2026","exact_match"),
      ("What is the reference ID for the GDPR audit due in September 2026?","AUDIT-EU-2025-441","exact_match")]),
    # Financial
    ("PF-011","The approved annual IT infrastructure budget for FY2026 is $4,750,000 and is tracked under cost center CC-IT-07.",
     [("What is the FY2026 IT infrastructure budget?","$4,750,000","exact_match"),
      ("Which cost center tracks the FY2026 IT budget?","CC-IT-07","exact_match"),
      ("What is the cost center for the $4,750,000 IT budget?","CC-IT-07","exact_match"),
      ("How much is budgeted for IT infrastructure in FY2026?","$4,750,000","exact_match"),
      ("State the FY2026 IT budget and its cost center.","$4,750,000 under CC-IT-07","exact_match")]),
    ("PF-012","The portfolio code for the emerging-markets equity fund is EMF-3B and its current NAV is $128.40 per unit.",
     [("What is the portfolio code for the emerging-markets equity fund?","EMF-3B","exact_match"),
      ("What is the NAV per unit for portfolio EMF-3B?","$128.40","exact_match"),
      ("Which portfolio has a NAV of $128.40?","EMF-3B","exact_match"),
      ("Name the fund associated with code EMF-3B.","emerging-markets equity fund","exact_match"),
      ("State the NAV and code for the emerging-markets equity fund.","EMF-3B at $128.40 per unit","exact_match")]),
    # Project Management
    ("PF-013","Sprint 47 runs from March 3 to March 17, 2026, and the sprint goal is to deliver the real-time notifications module.",
     [("What are the dates for Sprint 47?","March 3 to March 17, 2026","exact_match"),
      ("What is the goal of Sprint 47?","deliver the real-time notifications module","exact_match"),
      ("Which sprint runs March 3–17, 2026?","Sprint 47","exact_match"),
      ("When does Sprint 47 end?","March 17, 2026","exact_match"),
      ("What module must be delivered by the end of Sprint 47?","real-time notifications module","exact_match")]),
    ("PF-014","Milestone M-9 (beta launch) is scheduled for April 28, 2026, and is owned by project manager Desmond Okafor.",
     [("When is milestone M-9 scheduled?","April 28, 2026","exact_match"),
      ("Who owns milestone M-9?","Desmond Okafor","exact_match"),
      ("What does milestone M-9 represent?","beta launch","exact_match"),
      ("Which project manager is responsible for the beta launch milestone?","Desmond Okafor","exact_match"),
      ("Give the date and owner for milestone M-9.","April 28, 2026, owned by Desmond Okafor","exact_match")]),
    ("PF-015","Team Helios has a sprint velocity of 67 story points and a current capacity of 8 engineers.",
     [("What is Team Helios's sprint velocity?","67 story points","exact_match"),
      ("How many engineers are on Team Helios?","8","exact_match"),
      ("Which team has a velocity of 67 story points?","Team Helios","exact_match"),
      ("State the capacity of Team Helios.","8 engineers","exact_match"),
      ("What is the velocity and capacity of Team Helios?","67 story points, 8 engineers","exact_match")]),
    # General Technical
    ("PF-016","The primary load balancer is hosted at IP 10.0.4.22 and uses health-check path /api/health with a 5-second interval.",
     [("What is the IP of the primary load balancer?","10.0.4.22","exact_match"),
      ("What path does the load balancer use for health checks?","/api/health","exact_match"),
      ("How often does the health check run?","every 5 seconds","exact_match"),
      ("What is the health-check interval for the load balancer at 10.0.4.22?","5 seconds","exact_match"),
      ("State the health-check configuration for the primary load balancer.","path /api/health every 5 seconds","exact_match")]),
    ("PF-017","The SLA for the data-ingestion pipeline guarantees 99.5% uptime monthly and a maximum processing latency of 800 ms.",
     [("What uptime SLA applies to the data-ingestion pipeline?","99.5%","exact_match"),
      ("What is the maximum allowed latency for data ingestion?","800 ms","exact_match"),
      ("Over what period is the 99.5% uptime SLA measured?","monthly","exact_match"),
      ("State the latency guarantee for data ingestion.","800 ms","exact_match"),
      ("What are the two key SLA metrics for the data-ingestion pipeline?","99.5% monthly uptime and 800 ms max latency","exact_match")]),
    ("PF-018","Error code E-5502 indicates a downstream timeout on the payments gateway and triggers a PagerDuty alert to on-call rotation OC-PAY.",
     [("What does error code E-5502 mean?","downstream timeout on the payments gateway","exact_match"),
      ("Which PagerDuty rotation receives E-5502 alerts?","OC-PAY","exact_match"),
      ("What alert does error E-5502 trigger?","PagerDuty alert to on-call rotation OC-PAY","exact_match"),
      ("Which on-call rotation handles payments gateway timeouts?","OC-PAY","exact_match"),
      ("State the meaning and alert destination for error E-5502.","downstream payments gateway timeout, alerts OC-PAY","exact_match")]),
    ("PF-019","The Kubernetes namespace for the analytics workloads is kube-ns-analytics-prod and its resource quota is 64 CPU cores and 256 GB RAM.",
     [("What is the Kubernetes namespace for analytics production workloads?","kube-ns-analytics-prod","exact_match"),
      ("What CPU quota is set for kube-ns-analytics-prod?","64 CPU cores","exact_match"),
      ("What memory quota is set for kube-ns-analytics-prod?","256 GB RAM","exact_match"),
      ("Which namespace has a 64-core CPU quota?","kube-ns-analytics-prod","exact_match"),
      ("Give the resource quotas for the analytics production namespace.","64 CPU cores and 256 GB RAM","exact_match")]),
    ("PF-020","The TLS certificate for api.corp.internal expires on December 1, 2026, and is managed by team SecOps.",
     [("When does the TLS certificate for api.corp.internal expire?","December 1, 2026","exact_match"),
      ("Which team manages the api.corp.internal TLS certificate?","SecOps","exact_match"),
      ("What domain does the expiring TLS certificate belong to?","api.corp.internal","exact_match"),
      ("Who is responsible for the TLS certificate expiring in December 2026?","SecOps","exact_match"),
      ("State the expiry and owner for the api.corp.internal certificate.","December 1, 2026, managed by SecOps","exact_match")]),
    # Additional Software
    ("PF-021","Feature flag FEAT-DARK-MODE is enabled for 25% of users in the canary cohort starting from build 1.14.0.",
     [("What percentage of users get feature flag FEAT-DARK-MODE in canary?","25%","exact_match"),
      ("From which build version is FEAT-DARK-MODE available in canary?","1.14.0","exact_match"),
      ("Which feature flag is rolled out to 25% of the canary cohort?","FEAT-DARK-MODE","exact_match"),
      ("In which cohort is FEAT-DARK-MODE being tested?","canary cohort","exact_match"),
      ("What is the canary rollout percentage for FEAT-DARK-MODE?","25%","exact_match")]),
    ("PF-022","The database schema migration for table user_sessions is tracked in migration file 20260214_add_device_fingerprint.sql.",
     [("What is the migration file name for the user_sessions schema change?","20260214_add_device_fingerprint.sql","exact_match"),
      ("Which table is modified by migration 20260214_add_device_fingerprint.sql?","user_sessions","exact_match"),
      ("What column does migration 20260214 add to user_sessions?","device_fingerprint","exact_match"),
      ("Name the SQL file that migrates user_sessions.","20260214_add_device_fingerprint.sql","exact_match"),
      ("On what date was the user_sessions migration created (from filename)?","20260214","exact_match")]),
    ("PF-023","The default JWT expiry for mobile clients is 72 hours and for web clients is 24 hours, configurable via AUTH_TOKEN_TTL.",
     [("What is the JWT expiry for mobile clients?","72 hours","exact_match"),
      ("What is the JWT expiry for web clients?","24 hours","exact_match"),
      ("Which configuration key controls the JWT expiry?","AUTH_TOKEN_TTL","exact_match"),
      ("How much longer do mobile JWTs last compared to web JWTs?","48 hours longer","exact_match"),
      ("Name the env var used to configure JWT TTL.","AUTH_TOKEN_TTL","exact_match")]),
    ("PF-024","Microservice order-fulfillment-svc is deployed on port 8082 and communicates with inventory-svc on port 8091.",
     [("On which port is order-fulfillment-svc deployed?","8082","exact_match"),
      ("On which port does inventory-svc listen?","8091","exact_match"),
      ("Which service communicates with inventory-svc on port 8091?","order-fulfillment-svc","exact_match"),
      ("What is the port for inventory-svc?","8091","exact_match"),
      ("State the ports for order-fulfillment-svc and inventory-svc.","8082 and 8091","exact_match")]),
    ("PF-025","The Prometheus scrape interval for cluster metrics is 15 seconds and the retention period is 90 days.",
     [("What is the Prometheus scrape interval for cluster metrics?","15 seconds","exact_match"),
      ("What is the Prometheus retention period?","90 days","exact_match"),
      ("How often does Prometheus scrape cluster metrics?","every 15 seconds","exact_match"),
      ("For how long are Prometheus cluster metrics retained?","90 days","exact_match"),
      ("State the scrape interval and retention for Prometheus.","15 seconds scrape, 90 days retention","exact_match")]),
    # Biomedical continued
    ("PF-026","The placebo control arm for study APEX-7 contains 145 participants and uses saline injections as the sham treatment.",
     [("How many participants are in the APEX-7 placebo arm?","145","exact_match"),
      ("What sham treatment is used in the APEX-7 placebo arm?","saline injections","exact_match"),
      ("Which study has a 145-participant placebo arm?","APEX-7","exact_match"),
      ("What does the control arm receive in study APEX-7?","saline injections","exact_match"),
      ("State the placebo arm size and treatment for APEX-7.","145 participants receiving saline injections","exact_match")]),
    ("PF-027","The biomarker threshold for treatment eligibility is a serum IL-6 level above 12.5 pg/mL in protocol PRO-MED-33.",
     [("What biomarker threshold qualifies patients in PRO-MED-33?","serum IL-6 level above 12.5 pg/mL","exact_match"),
      ("Which biomarker is used for eligibility in PRO-MED-33?","serum IL-6","exact_match"),
      ("What is the minimum IL-6 level for eligibility in PRO-MED-33?","12.5 pg/mL","exact_match"),
      ("Name the protocol that uses an IL-6 threshold of 12.5 pg/mL.","PRO-MED-33","exact_match"),
      ("What unit is used for the IL-6 eligibility threshold?","pg/mL","exact_match")]),
    # Financial continued
    ("PF-028","The foreign exchange hedge ratio for EUR/USD exposure is 65%, reviewed quarterly under policy FX-POL-2024.",
     [("What is the EUR/USD hedge ratio?","65%","exact_match"),
      ("How often is the hedge ratio reviewed?","quarterly","exact_match"),
      ("Which policy governs the EUR/USD hedge?","FX-POL-2024","exact_match"),
      ("State the hedge ratio and review frequency for EUR/USD.","65%, reviewed quarterly","exact_match"),
      ("Name the FX policy that sets a 65% hedge ratio.","FX-POL-2024","exact_match")]),
    ("PF-029","The maximum drawdown limit for fund APEX-BOND-II is 8% and breaching it triggers a mandatory risk review.",
     [("What is the maximum drawdown limit for APEX-BOND-II?","8%","exact_match"),
      ("What happens if APEX-BOND-II exceeds its drawdown limit?","mandatory risk review","exact_match"),
      ("Which fund has an 8% drawdown limit?","APEX-BOND-II","exact_match"),
      ("What triggers a mandatory risk review in APEX-BOND-II?","breaching the 8% maximum drawdown","exact_match"),
      ("State the drawdown limit and consequence for APEX-BOND-II.","8% limit, triggers mandatory risk review","exact_match")]),
    # Legal continued
    ("PF-030","Regulatory filing reference REG-FIN-2026-009 must be submitted by March 31, 2026 to the Financial Conduct Authority.",
     [("What is the deadline for regulatory filing REG-FIN-2026-009?","March 31, 2026","exact_match"),
      ("To which authority must REG-FIN-2026-009 be submitted?","Financial Conduct Authority","exact_match"),
      ("What is the reference number for the March 2026 FCA filing?","REG-FIN-2026-009","exact_match"),
      ("Name the regulator receiving filing REG-FIN-2026-009.","Financial Conduct Authority","exact_match"),
      ("When is REG-FIN-2026-009 due?","March 31, 2026","exact_match")]),
    # Project management continued
    ("PF-031","Risk register item RR-014 has a probability of 0.4 and an impact score of 9 on a 10-point scale, placing it in the critical zone.",
     [("What is the probability of risk register item RR-014?","0.4","exact_match"),
      ("What impact score does RR-014 have?","9","exact_match"),
      ("In which zone does RR-014 fall?","critical zone","exact_match"),
      ("What scale is used for the RR-014 impact score?","10-point scale","exact_match"),
      ("State the probability and impact for RR-014.","probability 0.4, impact 9 out of 10","exact_match")]),
    ("PF-032","The change-request window for production deployments is every Tuesday from 22:00 to 02:00 UTC.",
     [("When is the production deployment change window?","every Tuesday from 22:00 to 02:00 UTC","exact_match"),
      ("What timezone governs the production change-request window?","UTC","exact_match"),
      ("On which day are production deployments allowed?","Tuesday","exact_match"),
      ("What time does the production change window open?","22:00 UTC","exact_match"),
      ("How long is the weekly production deployment window?","4 hours","exact_match")]),
    # Server / technical
    ("PF-033","Object storage bucket backups-prod-eu is replicated to region eu-west-2 with a replication lag SLA of under 60 seconds.",
     [("Which region is backups-prod-eu replicated to?","eu-west-2","exact_match"),
      ("What is the replication lag SLA for backups-prod-eu?","under 60 seconds","exact_match"),
      ("Name the storage bucket that replicates to eu-west-2.","backups-prod-eu","exact_match"),
      ("What storage bucket has a 60-second replication SLA?","backups-prod-eu","exact_match"),
      ("State the replication target and lag SLA for backups-prod-eu.","eu-west-2 with under 60 seconds lag","exact_match")]),
    ("PF-034","The Kafka topic for order-events has 12 partitions and a retention of 7 days with key-based compaction disabled.",
     [("How many partitions does the order-events Kafka topic have?","12","exact_match"),
      ("What is the retention period for the order-events Kafka topic?","7 days","exact_match"),
      ("Is key-based compaction enabled on order-events?","No","exact_match"),
      ("State the partition count for order-events.","12 partitions","exact_match"),
      ("What is the order-events Kafka topic retention?","7 days","exact_match")]),
    ("PF-035","The GraphQL API schema version is v2024-11 and it is pinned in the developer portal under gateway config GW-CONF-88.",
     [("What is the current GraphQL API schema version?","v2024-11","exact_match"),
      ("Where is the GraphQL schema version pinned?","developer portal under gateway config GW-CONF-88","exact_match"),
      ("What config ID pins the GraphQL schema version?","GW-CONF-88","exact_match"),
      ("Name the gateway config that locks the GraphQL schema.","GW-CONF-88","exact_match"),
      ("State the GraphQL schema version and its config location.","v2024-11 under GW-CONF-88","exact_match")]),
    ("PF-036","The on-call escalation policy EscPol-3 routes unacknowledged alerts to the VP of Engineering after 15 minutes.",
     [("Which escalation policy routes alerts to the VP of Engineering?","EscPol-3","exact_match"),
      ("After how many minutes does EscPol-3 escalate unacknowledged alerts?","15 minutes","exact_match"),
      ("To whom does EscPol-3 escalate after 15 minutes?","VP of Engineering","exact_match"),
      ("What condition triggers escalation under EscPol-3?","unacknowledged alerts","exact_match"),
      ("State the escalation timeline under policy EscPol-3.","15 minutes before escalating to VP of Engineering","exact_match")]),
    ("PF-037","The canary deployment threshold for rollback is a 5% increase in 5xx error rate measured over a 10-minute window.",
     [("What error rate increase triggers a canary rollback?","5%","exact_match"),
      ("Over what time window is the canary error rate measured?","10 minutes","exact_match"),
      ("Which HTTP status class is monitored for canary rollbacks?","5xx","exact_match"),
      ("State the canary rollback criteria.","5% increase in 5xx error rate over 10 minutes","exact_match"),
      ("How is the 5xx rate window defined for canary rollback?","10-minute window","exact_match")]),
    ("PF-038","The data warehouse refresh job DW-JOB-NIGHTLY runs at 02:30 UTC and loads data from source schema raw_ingest.",
     [("What time does DW-JOB-NIGHTLY run?","02:30 UTC","exact_match"),
      ("Which source schema does DW-JOB-NIGHTLY load from?","raw_ingest","exact_match"),
      ("What is the job ID for the nightly data warehouse refresh?","DW-JOB-NIGHTLY","exact_match"),
      ("Name the schema that feeds the nightly warehouse job.","raw_ingest","exact_match"),
      ("State the schedule and source for DW-JOB-NIGHTLY.","02:30 UTC from raw_ingest","exact_match")]),
    ("PF-039","Service mesh mutual TLS enforcement is enabled for all inter-service calls within namespace kube-ns-core using policy MTLS-POL-01.",
     [("Is mTLS enforced in kube-ns-core?","Yes","exact_match"),
      ("Which policy enforces mTLS in kube-ns-core?","MTLS-POL-01","exact_match"),
      ("What namespace uses mTLS policy MTLS-POL-01?","kube-ns-core","exact_match"),
      ("For what type of calls is mTLS required in kube-ns-core?","all inter-service calls","exact_match"),
      ("Name the mTLS policy applied in the core namespace.","MTLS-POL-01","exact_match")]),
    ("PF-040","The model registry entry for fraud-detection-v4 is at artifact path s3://models-prod/fraud/v4/model.pkl.",
     [("What is the artifact path for fraud-detection-v4?","s3://models-prod/fraud/v4/model.pkl","exact_match"),
      ("Which model is stored at s3://models-prod/fraud/v4/model.pkl?","fraud-detection-v4","exact_match"),
      ("What S3 bucket holds the fraud detection model?","models-prod","exact_match"),
      ("State the full artifact URI for fraud-detection-v4.","s3://models-prod/fraud/v4/model.pkl","exact_match"),
      ("What file extension does the fraud-detection-v4 model have?","pkl","exact_match")]),
]

# ── TYPE 2: GROUNDED REASONING (PF-041 to PF-075) ─────────────────────────────

GROUNDED = [
    ("PF-041",
     "The approved vendor shortlist budget cap is $120,000. Vendor Nexalink submitted a quote of $135,000 for the network upgrade project.",
     [("Is Vendor Nexalink within the approved budget cap? Explain.","No","keyword_rule",["no","135","120","over budget","exceeds"],"no"),
      ("By how much does Nexalink's quote exceed the budget cap?","$15,000","exact_match"),
      ("Can Nexalink be selected without a budget exception? Why?","No, because their quote exceeds the $120,000 cap","keyword_rule",["no","exceeds","120"],"no"),
      ("What is the gap between the budget cap and Nexalink's quote?","$15,000","exact_match"),
      ("Should Nexalink proceed to contract? Justify.","No","keyword_rule",["no","over","budget","exception"],"no")]),
    ("PF-042",
     "The maximum allowed server provisioning time is 4 hours per SLA. The DevOps team provisioned server SRV-994 in 5 hours 20 minutes.",
     [("Did the provisioning of SRV-994 meet the SLA? Explain.","No","keyword_rule",["no","5 hours","exceeds","violation","breach"],"no"),
      ("By how much did SRV-994 provisioning exceed the SLA?","1 hour 20 minutes","exact_match"),
      ("What is the SLA limit for server provisioning?","4 hours","exact_match"),
      ("Was the SLA breached for SRV-994?","Yes","keyword_rule",["yes","breach","exceeded","violation"],"yes"),
      ("State the SLA outcome for SRV-994.","SLA breached by 1 hour 20 minutes","keyword_rule",["breach","1 hour 20"],"breached")]),
    ("PF-043",
     "Team Aurora's sprint capacity is 54 story points. The product owner has requested 71 story points of work for the upcoming sprint.",
     [("Can Team Aurora complete all requested work in the sprint?","No","keyword_rule",["no","54","71","exceeds","over capacity"],"no"),
      ("How many story points exceed Team Aurora's capacity?","17","exact_match"),
      ("What is Team Aurora's sprint capacity?","54 story points","exact_match"),
      ("What is the overloading amount for Team Aurora's sprint?","17 story points","exact_match"),
      ("Should the product owner reduce scope? Why?","Yes","keyword_rule",["yes","exceed","capacity","54","reduce"],"yes")]),
    ("PF-044",
     "The server disk threshold for alerting is 85% utilization. Server DB-PRIMARY-02 currently shows 91% disk utilization.",
     [("Should an alert fire for DB-PRIMARY-02?","Yes","keyword_rule",["yes","91%","85%","exceeds","threshold"],"yes"),
      ("By how much does DB-PRIMARY-02 exceed the disk alert threshold?","6%","exact_match"),
      ("What is the disk utilization alert threshold?","85%","exact_match"),
      ("Is DB-PRIMARY-02 above or below the alert threshold?","above","keyword_rule",["above","exceeds","91%"],"above"),
      ("What action should be taken for DB-PRIMARY-02?","Trigger an alert","keyword_rule",["alert","threshold","exceeded"],"alert")]),
    ("PF-045",
     "The contractual uptime guarantee is 99.9% per month. The service experienced 6 hours of downtime in March 2026 (744-hour month).",
     [("Was the uptime SLA met in March 2026?","No","keyword_rule",["no","0.81%","99.19%","6 hours","breach"],"no"),
      ("What was the actual uptime percentage in March 2026?","99.19%","exact_match"),
      ("What is the maximum allowed monthly downtime for 99.9% SLA?","0.744 hours","exact_match"),
      ("By how many hours did the service exceed the downtime allowance?","5.256 hours","exact_match"),
      ("Was a credit or penalty triggered under the SLA?","Yes","keyword_rule",["yes","breach","penalty","credit","exceeded"],"yes")]),
    ("PF-046",
     "The maximum memory allocation per container is 4 GB. Container worker-batch-7 is configured with a 6 GB memory limit.",
     [("Is container worker-batch-7 correctly configured?","No","keyword_rule",["no","6 GB","exceeds","4 GB","over limit"],"no"),
      ("By how much does worker-batch-7 exceed the memory limit?","2 GB","exact_match"),
      ("What is the per-container memory cap?","4 GB","exact_match"),
      ("Should worker-batch-7 be redeployed with corrected settings?","Yes","keyword_rule",["yes","exceed","4 GB","correct","redeploy"],"yes"),
      ("What memory value should worker-batch-7 use?","4 GB or less","keyword_rule",["4 GB","maximum","reduce","correct"],"4 GB or less")]),
    ("PF-047",
     "Clinical protocol PRO-CARD-5 requires a minimum of 200 participants for statistical power. Enrollment has reached 187 participants.",
     [("Has protocol PRO-CARD-5 met its enrollment requirement?","No","keyword_rule",["no","187","200","below","insufficient"],"no"),
      ("How many more participants are needed to meet PRO-CARD-5's requirement?","13","exact_match"),
      ("Can PRO-CARD-5 proceed to analysis?","No","keyword_rule",["no","200","below","underpowered","insufficient"],"no"),
      ("What is the enrollment gap in PRO-CARD-5?","13 participants","exact_match"),
      ("Is PRO-CARD-5 statistically powered?","No","keyword_rule",["no","below","underpowered","187","200"],"no")]),
    ("PF-048",
     "The loan-to-value ratio ceiling for commercial mortgages is 70%. Applicant firm WestEdge Corp applied for a loan at 78% LTV.",
     [("Does WestEdge Corp's application comply with the LTV ceiling?","No","keyword_rule",["no","78%","70%","exceeds","non-compliant"],"no"),
      ("By how much does WestEdge's LTV exceed the ceiling?","8%","exact_match"),
      ("What is the maximum LTV for commercial mortgages?","70%","exact_match"),
      ("Should WestEdge Corp's application be approved as submitted?","No","keyword_rule",["no","exceeds","70%","ceiling"],"no"),
      ("What LTV ceiling applies to commercial mortgages?","70%","exact_match")]),
    ("PF-049",
     "The regulatory body requires a maximum of 14 business days to process a variance request. Request VAR-2026-118 was submitted on January 5 and approved on January 26 (15 business days).",
     [("Was VAR-2026-118 processed within the regulatory deadline?","No","keyword_rule",["no","15","14","exceeded","breach"],"no"),
      ("By how many business days was VAR-2026-118 late?","1","exact_match"),
      ("What is the regulatory time limit for variance requests?","14 business days","exact_match"),
      ("When was VAR-2026-118 approved?","January 26","exact_match"),
      ("Is there a compliance issue with VAR-2026-118?","Yes","keyword_rule",["yes","breach","15 days","14 days","exceeded"],"yes")]),
    ("PF-050",
     "The quarterly marketing budget is $500,000. Campaigns run so far this quarter total $487,000. A new campaign costing $20,000 is proposed.",
     [("Can the proposed $20,000 campaign be funded from the current quarter budget?","No","keyword_rule",["no","7,000","over","487","500","exceeds"],"no"),
      ("What is the remaining budget after existing campaigns?","$13,000","exact_match"),
      ("By how much would the new campaign exceed the quarterly budget?","$7,000","exact_match"),
      ("Can the full campaign run within this quarter's budget?","No","keyword_rule",["no","exceed","13,000","7,000"],"no"),
      ("What percentage of the budget has already been spent?","97.4%","exact_match")]),
    ("PF-051",
     "The minimum A/B test sample size for 80% statistical power is 1,000 users per variant. Variant B has accumulated 820 users.",
     [("Does Variant B have sufficient sample size?","No","keyword_rule",["no","820","1,000","below","insufficient"],"no"),
      ("How many more users does Variant B need?","180","exact_match"),
      ("What is the minimum sample per variant?","1,000 users","exact_match"),
      ("Can Variant B results be analyzed for 80% power?","No","keyword_rule",["no","820","underpowered","insufficient","below 1,000"],"no"),
      ("What is the shortfall in Variant B's sample?","180 users","exact_match")]),
    ("PF-052",
     "The maximum response time for Tier-1 support tickets is 2 hours. Ticket T1-8844 was opened at 09:00 and first responded to at 11:45.",
     [("Was the Tier-1 SLA met for ticket T1-8844?","No","keyword_rule",["no","2 hours 45","2:45","breached","exceeded"],"no"),
      ("How long did it take to respond to T1-8844?","2 hours 45 minutes","exact_match"),
      ("By how much was the Tier-1 SLA breached for T1-8844?","45 minutes","exact_match"),
      ("What is the Tier-1 response time SLA?","2 hours","exact_match"),
      ("Was ticket T1-8844 a SLA breach?","Yes","keyword_rule",["yes","breach","2 hours","2:45","exceeded"],"yes")]),
    ("PF-053",
     "Drug compound IDP-5533 must remain below 40°C during shipping. A batch was transported at 44°C for 3 hours.",
     [("Was the IDP-5533 batch shipped within temperature limits?","No","keyword_rule",["no","44°C","40°C","exceeded","excursion"],"no"),
      ("By how many degrees did the shipping temperature exceed the limit?","4°C","exact_match"),
      ("What is the maximum shipping temperature for IDP-5533?","40°C","exact_match"),
      ("Is the batch compromised per shipping protocol?","Yes","keyword_rule",["yes","excursion","44°C","exceed","quarantine"],"yes"),
      ("How long was IDP-5533 exposed to excess temperature?","3 hours","exact_match")]),
    ("PF-054",
     "The change freeze period runs from December 15 to January 5. A deployment to production was made on December 20.",
     [("Was the December 20 deployment compliant with the change freeze?","No","keyword_rule",["no","freeze","December 20","prohibited","violation"],"no"),
      ("When does the change freeze period start?","December 15","exact_match"),
      ("When does the change freeze period end?","January 5","exact_match"),
      ("Was December 20 inside the change freeze window?","Yes","keyword_rule",["yes","within","freeze","December 15","January 5"],"yes"),
      ("What policy violation occurred with the December 20 deployment?","Deploying during a change freeze period","keyword_rule",["freeze","violation","prohibited","December 20"],"change freeze violation")]),
    ("PF-055",
     "The maximum allowable packet loss threshold is 0.1%. The network monitor reports 0.3% packet loss on link LINK-WAN-07.",
     [("Is LINK-WAN-07 within acceptable packet loss?","No","keyword_rule",["no","0.3%","0.1%","exceeds","above"],"no"),
      ("By how much does LINK-WAN-07 exceed the packet loss threshold?","0.2%","exact_match"),
      ("What is the maximum allowable packet loss?","0.1%","exact_match"),
      ("Should LINK-WAN-07 trigger an alert?","Yes","keyword_rule",["yes","alert","0.3%","exceeds","threshold"],"yes"),
      ("What is the current packet loss on LINK-WAN-07?","0.3%","exact_match")]),
    ("PF-056",
     "The architecture review board requires review for any service handling more than 10,000 requests per second. Service analytics-aggregator peaks at 14,500 RPS.",
     [("Does analytics-aggregator require an architecture review?","Yes","keyword_rule",["yes","14,500","10,000","exceeds","requires review"],"yes"),
      ("By how much does analytics-aggregator exceed the ARB threshold?","4,500 RPS","exact_match"),
      ("What is the ARB review threshold?","10,000 requests per second","exact_match"),
      ("What service peaks at 14,500 RPS?","analytics-aggregator","exact_match"),
      ("Is analytics-aggregator above or below the ARB review threshold?","above","keyword_rule",["above","exceeds","14,500","10,000"],"above")]),
    ("PF-057",
     "The minimum capital reserve ratio is 12%. Bank subsidiary CorpBank-NE reports a current capital ratio of 10.8%.",
     [("Is CorpBank-NE meeting the minimum capital reserve requirement?","No","keyword_rule",["no","10.8%","12%","below","deficient"],"no"),
      ("By how much is CorpBank-NE below the minimum capital ratio?","1.2%","exact_match"),
      ("What is the minimum capital reserve ratio?","12%","exact_match"),
      ("What is CorpBank-NE's current capital ratio?","10.8%","exact_match"),
      ("Is regulatory intervention required for CorpBank-NE?","Yes","keyword_rule",["yes","below","12%","deficient","intervention"],"yes")]),
    ("PF-058",
     "Project X has a runway of 8 months. It requires 4 engineers for 6 months and 2 engineers for the remaining 2 months.",
     [("Is Project X's resource plan feasible within its 8-month runway?","Yes","keyword_rule",["yes","6 months","2 months","8 months","feasible","within"],"yes"),
      ("How many engineers are needed in the second phase of Project X?","2","exact_match"),
      ("How long is the first phase of Project X?","6 months","exact_match"),
      ("What is the total runway for Project X?","8 months","exact_match"),
      ("Does the phased engineer plan sum to the project runway?","Yes","keyword_rule",["yes","6 plus 2","8 months","sum","equals"],"yes")]),
    ("PF-059",
     "The content delivery network caches assets for 72 hours. The marketing team updated an image asset and expects it to be live immediately.",
     [("Will the updated image appear immediately to all users?","No","keyword_rule",["no","72 hours","cache","propagation","delay"],"no"),
      ("How long is the CDN cache duration?","72 hours","exact_match"),
      ("What is the issue with the marketing team's expectation?","Assets are cached for 72 hours so changes are not immediate","keyword_rule",["72 hours","cache","not immediate","delay"],"cache delay"),
      ("What must the team do to force immediate cache refresh?","Invalidate or purge the CDN cache","keyword_rule",["invalidate","purge","cache","bust","refresh"],"cache invalidation"),
      ("When will all CDN nodes serve the updated image without purging?","After 72 hours","exact_match")]),
    ("PF-060",
     "The maximum file upload size is 50 MB. A user attempted to upload a video file of 73 MB.",
     [("Was the 73 MB upload successful?","No","keyword_rule",["no","73 MB","50 MB","exceeds","rejected"],"no"),
      ("By how much did the upload exceed the size limit?","23 MB","exact_match"),
      ("What is the maximum upload size?","50 MB","exact_match"),
      ("Should the upload be rejected?","Yes","keyword_rule",["yes","reject","exceeds","50 MB","73 MB"],"yes"),
      ("What error type should the system return?","File too large","keyword_rule",["too large","exceeds","50 MB","size limit","rejected"],"file too large")]),
    ("PF-061",
     "The peer review policy requires at least 2 approvals before merging to the main branch. Pull request PR-7712 has received 1 approval.",
     [("Can PR-7712 be merged now?","No","keyword_rule",["no","1 approval","2 approvals","insufficient","missing"],"no"),
      ("How many approvals does PR-7712 still need?","1","exact_match"),
      ("What is the minimum approval count for merging?","2","exact_match"),
      ("Is PR-7712 ready to merge?","No","keyword_rule",["no","1","2","approval","missing","requires"],"no"),
      ("What must happen before PR-7712 can merge?","It needs 1 more approval","keyword_rule",["1 more","additional","approval","reviewer"],"1 more approval")]),
    ("PF-062",
     "Automated backups run every 6 hours. The last successful backup completed at 06:00. It is now 14:30.",
     [("Is a backup overdue?","Yes","keyword_rule",["yes","overdue","8.5 hours","12:00","missed","8 hours"],"yes"),
      ("When was the last successful backup?","06:00","exact_match"),
      ("How many backup cycles have been missed since 06:00?","1","exact_match"),
      ("What time should the next backup have run?","12:00","exact_match"),
      ("By how much is the backup overdue at 14:30?","2 hours 30 minutes","exact_match")]),
    ("PF-063",
     "Penetration test report PT-2025-77 found 3 critical vulnerabilities. The remediation SLA for critical findings is 72 hours.",
     [("How many critical vulnerabilities were found in PT-2025-77?","3","exact_match"),
      ("What is the remediation SLA for critical vulnerabilities?","72 hours","exact_match"),
      ("Which report number contains 3 critical findings?","PT-2025-77","exact_match"),
      ("If PT-2025-77 was issued on Monday at 09:00, what is the remediation deadline?","Thursday at 09:00","keyword_rule",["Thursday","09:00","72 hours","three days"],"Thursday 09:00"),
      ("What category of findings has a 72-hour SLA?","critical","exact_match")]),
    ("PF-064",
     "The API deprecation policy allows deprecated endpoints to remain active for exactly 6 months after the deprecation notice. Endpoint /v1/users was deprecated on October 1, 2025.",
     [("When will endpoint /v1/users be decommissioned?","April 1, 2026","exact_match"),
      ("How long is the deprecation grace period?","6 months","exact_match"),
      ("Which endpoint was deprecated on October 1, 2025?","/v1/users","exact_match"),
      ("Has /v1/users been decommissioned as of March 2026?","No","keyword_rule",["no","April 2026","still active","grace period"],"no"),
      ("When did the /v1/users deprecation notice go out?","October 1, 2025","exact_match")]),
    ("PF-065",
     "The minimum password length policy is 12 characters. User account acct-Fernwood was created with a password of 9 characters.",
     [("Does acct-Fernwood's password meet the policy?","No","keyword_rule",["no","9","12","below","non-compliant"],"no"),
      ("By how many characters is acct-Fernwood's password short?","3","exact_match"),
      ("What is the minimum password length?","12 characters","exact_match"),
      ("Should acct-Fernwood be required to reset their password?","Yes","keyword_rule",["yes","reset","non-compliant","9","12"],"yes"),
      ("Is acct-Fernwood's password policy-compliant?","No","keyword_rule",["no","9 characters","12 characters","too short"],"no")]),
    ("PF-066",
     "The maximum number of failed login attempts before lockout is 5. User acct-MORLAND has failed 5 attempts in the last 10 minutes.",
     [("Should acct-MORLAND be locked out?","Yes","keyword_rule",["yes","5 attempts","lockout","threshold","reached"],"yes"),
      ("What is the lockout threshold?","5 failed attempts","exact_match"),
      ("How many failed attempts has acct-MORLAND made?","5","exact_match"),
      ("Has acct-MORLAND reached the lockout threshold?","Yes","keyword_rule",["yes","5","threshold","reached"],"yes"),
      ("What action should the system take for acct-MORLAND?","Lock the account","keyword_rule",["lock","lockout","5 attempts","threshold"],"account lockout")]),
    ("PF-067",
     "The CI build pipeline must pass all unit tests before a merge is allowed. Build B-9924 has 3 failing unit tests.",
     [("Can build B-9924 be merged?","No","keyword_rule",["no","3 failing","tests must pass","cannot merge"],"no"),
      ("How many failing unit tests does build B-9924 have?","3","exact_match"),
      ("What condition must be met before merging?","All unit tests must pass","exact_match"),
      ("Is build B-9924 in a mergeable state?","No","keyword_rule",["no","3 failing","tests fail","not mergeable"],"no"),
      ("What must be resolved before B-9924 can merge?","The 3 failing unit tests","keyword_rule",["3 failing","unit tests","resolve","fix"],"failing tests")]),
    ("PF-068",
     "The supply chain policy requires dual-source vendors for any component with a single-source risk score above 7. Component PCB-CTRL-55 has a risk score of 8.5.",
     [("Does PCB-CTRL-55 require dual-source vendors?","Yes","keyword_rule",["yes","8.5","7","above","dual-source","requires"],"yes"),
      ("What is the risk score threshold for dual-sourcing?","7","exact_match"),
      ("What is the risk score of PCB-CTRL-55?","8.5","exact_match"),
      ("Is PCB-CTRL-55 above the dual-source threshold?","Yes","keyword_rule",["yes","8.5","above 7","exceeds"],"yes"),
      ("What sourcing action is required for PCB-CTRL-55?","Dual-source vendors","keyword_rule",["dual-source","two vendors","second supplier","8.5","policy"],"dual-source")]),
    ("PF-069",
     "The incident response policy mandates a post-mortem within 5 business days of resolution. Incident INC-2026-044 was resolved on February 10.",
     [("When is the post-mortem due for INC-2026-044?","February 17","exact_match"),
      ("What is the post-mortem deadline from resolution?","5 business days","exact_match"),
      ("When was INC-2026-044 resolved?","February 10","exact_match"),
      ("Is a post-mortem mandatory for INC-2026-044?","Yes","keyword_rule",["yes","mandatory","policy","5 business days"],"yes"),
      ("What document must be produced after INC-2026-044?","A post-mortem","keyword_rule",["post-mortem","5 business days","incident response"],"post-mortem")]),
    ("PF-070",
     "The data retention policy mandates deletion of PII after 3 years. A record set tagged user-cohort-2021-Q1 was created in January 2021.",
     [("Should user-cohort-2021-Q1 data have been deleted by now (March 2026)?","Yes","keyword_rule",["yes","January 2024","3 years","expired","delete"],"yes"),
      ("When was user-cohort-2021-Q1 created?","January 2021","exact_match"),
      ("What is the PII retention limit?","3 years","exact_match"),
      ("By when should user-cohort-2021-Q1 have been deleted?","January 2024","exact_match"),
      ("Is retaining user-cohort-2021-Q1 a policy violation?","Yes","keyword_rule",["yes","violation","expired","3 years","January 2024"],"yes")]),
    ("PF-071",
     "The energy efficiency rating threshold for procurement is a minimum PUE of 1.4 or better (lower is better). Data center DC-APEX-3 has a PUE of 1.6.",
     [("Does DC-APEX-3 meet the procurement energy threshold?","No","keyword_rule",["no","1.6","1.4","above","fails","worse"],"no"),
      ("What is the maximum acceptable PUE for procurement?","1.4","exact_match"),
      ("What is DC-APEX-3's PUE?","1.6","exact_match"),
      ("Is DC-APEX-3's PUE better or worse than the threshold?","worse","keyword_rule",["worse","higher","1.6","1.4","fails"],"worse"),
      ("Can DC-APEX-3 be procured under the energy efficiency policy?","No","keyword_rule",["no","1.6","1.4","fails","exceeds"],"no")]),
    ("PF-072",
     "The maximum batch job runtime is 6 hours. Batch job BATCH-RPT-MONTHLY has been running for 7 hours 15 minutes.",
     [("Is BATCH-RPT-MONTHLY within its allowed runtime?","No","keyword_rule",["no","7 hours","6 hours","exceeded","overtime"],"no"),
      ("By how much has BATCH-RPT-MONTHLY exceeded its time limit?","1 hour 15 minutes","exact_match"),
      ("What is the maximum allowed batch job runtime?","6 hours","exact_match"),
      ("Should BATCH-RPT-MONTHLY be terminated?","Yes","keyword_rule",["yes","terminate","exceeded","6 hours","overtime"],"yes"),
      ("How long has BATCH-RPT-MONTHLY been running?","7 hours 15 minutes","exact_match")]),
    ("PF-073",
     "The open-source license policy prohibits GPL-licensed libraries in commercial products. Library log-rapid v2.1 is GPL-3.0 licensed.",
     [("Can log-rapid v2.1 be used in a commercial product?","No","keyword_rule",["no","GPL","prohibited","commercial","policy"],"no"),
      ("What license does log-rapid v2.1 carry?","GPL-3.0","exact_match"),
      ("Which license type is prohibited in commercial products?","GPL","exact_match"),
      ("Should log-rapid v2.1 be included in the project dependency list?","No","keyword_rule",["no","GPL","prohibited","commercial","remove"],"no"),
      ("What must happen if log-rapid v2.1 is already in the codebase?","It must be removed or replaced with a compatible license","keyword_rule",["remove","replace","GPL","commercial","incompatible"],"must be removed")]),
    ("PF-074",
     "The application requires a minimum of 4 GB free RAM to launch. The target host machine has 2 GB free RAM.",
     [("Can the application launch on the target host?","No","keyword_rule",["no","2 GB","4 GB","insufficient","not enough RAM"],"no"),
      ("How much free RAM does the target host have?","2 GB","exact_match"),
      ("What is the minimum free RAM required?","4 GB","exact_match"),
      ("By how much RAM is the host below the minimum?","2 GB","exact_match"),
      ("Should the application be deployed to this host?","No","keyword_rule",["no","2 GB","insufficient","4 GB","below"],"no")]),
    ("PF-075",
     "The firewall rule permits inbound traffic on port 443 only. An application is attempting to bind to port 8080 for external access.",
     [("Will port 8080 receive external traffic through the firewall?","No","keyword_rule",["no","8080","443","blocked","not permitted"],"no"),
      ("Which port is permitted by the firewall?","443","exact_match"),
      ("Which port is the application attempting to use?","8080","exact_match"),
      ("Is the application's port request compliant with the firewall rule?","No","keyword_rule",["no","8080","443","blocked","not allowed"],"no"),
      ("What change is needed for the application to receive external traffic?","The application must use port 443 or the firewall rule must be updated","keyword_rule",["443","port","firewall","change","update","use 443"],"use port 443")]),
]

# ── TYPE 3: IMPLICIT CONTEXT / PRIORITY COMPLIANCE (PF-076 to PF-100) ─────────

IMPLICIT = [
    ("PF-076",
     "CRITICAL SYSTEM REQUIREMENT: All API responses MUST include a timestamp field in ISO 8601 format. This is mandatory for audit compliance.",
     [("Design the response schema for the /orders endpoint.","timestamp field required","constraint_compliance"),
      ("What fields must every API response contain?","timestamp","exact_match"),
      ("Design a user profile API response.","timestamp field required","constraint_compliance"),
      ("Create a payment confirmation API response schema.","timestamp field required","constraint_compliance"),
      ("List the mandatory fields in all API responses.","timestamp","exact_match")]),
    ("PF-077",
     "BINDING REQUIREMENT: Every database write operation MUST be wrapped in a transaction with rollback on failure. No exceptions.",
     [("Write the schema for the order-creation service database layer.","transaction","constraint_compliance"),
      ("What must surround all database write operations?","transaction","exact_match"),
      ("Design the user registration database handler.","transaction with rollback","constraint_compliance"),
      ("What happens on a failed database write?","rollback","exact_match"),
      ("Create the payment record insertion logic.","transaction","constraint_compliance")]),
    ("PF-078",
     "MANDATORY SECURITY POLICY: All passwords must be hashed using bcrypt with a minimum cost factor of 12 before storage.",
     [("Design the user authentication storage schema.","bcrypt cost factor 12","constraint_compliance"),
      ("What algorithm must be used for password hashing?","bcrypt","exact_match"),
      ("What is the minimum bcrypt cost factor?","12","exact_match"),
      ("Create the user registration password handling code.","bcrypt","constraint_compliance"),
      ("How must passwords be stored in the system?","bcrypt with cost factor 12","exact_match")]),
    ("PF-079",
     "ARCHITECTURAL MANDATE: The system must support horizontal scaling. All services must be stateless — no session state may be stored in application memory.",
     [("Design the session management approach for the user portal.","stateless","constraint_compliance"),
      ("Where must session state NOT be stored?","application memory","exact_match"),
      ("Design the cart service architecture.","stateless","constraint_compliance"),
      ("What scaling model is required?","horizontal scaling","exact_match"),
      ("Create the authentication middleware design.","stateless","constraint_compliance")]),
    ("PF-080",
     "COMPLIANCE RULE: All log entries containing PII must be masked before writing to any log store. PII includes email addresses, phone numbers, and SSNs.",
     [("Design the logging middleware for the user service.","PII masking","constraint_compliance"),
      ("What three types of data must be masked in logs?","email addresses, phone numbers, and SSNs","exact_match"),
      ("Create the audit log schema for the payment service.","PII masked","constraint_compliance"),
      ("What must happen to PII before it is written to logs?","masked","exact_match"),
      ("Design the error logging pipeline for the API gateway.","PII masking","constraint_compliance")]),
    ("PF-081",
     "HARD REQUIREMENT: The maximum API response time for any endpoint is 500 ms under P99 load. Endpoints exceeding this must be optimized or cached.",
     [("Design the SLA monitoring dashboard.","500 ms P99","constraint_compliance"),
      ("What is the P99 response time limit?","500 ms","exact_match"),
      ("What must happen if an endpoint exceeds 500 ms P99?","optimized or cached","exact_match"),
      ("Set up alerting thresholds for the API gateway.","500 ms","constraint_compliance"),
      ("Design the performance test acceptance criteria.","500 ms P99","constraint_compliance")]),
    ("PF-082",
     "REGULATORY MANDATE: All financial transactions above $10,000 must be automatically flagged for AML (anti-money laundering) review.",
     [("Design the transaction processing pipeline.","AML flag above $10,000","constraint_compliance"),
      ("What threshold triggers AML review?","$10,000","exact_match"),
      ("What does AML stand for in this context?","anti-money laundering","exact_match"),
      ("Create the transaction monitoring rule set.","flag transactions above $10,000","constraint_compliance"),
      ("Design the compliance reporting module for transactions.","AML flag $10,000","constraint_compliance")]),
    ("PF-083",
     "CRITICAL OPERATIONAL RULE: The system must emit a heartbeat event every 30 seconds to the monitoring bus. Absence of heartbeat triggers a P1 incident.",
     [("Design the service health reporting module.","heartbeat every 30 seconds","constraint_compliance"),
      ("What event frequency is required from each service?","every 30 seconds","exact_match"),
      ("What incident priority triggers if heartbeat is absent?","P1","exact_match"),
      ("Design the monitoring integration for a new microservice.","30-second heartbeat","constraint_compliance"),
      ("Create the liveness check implementation.","heartbeat 30 seconds","constraint_compliance")]),
    ("PF-084",
     "SECURITY STANDARD: All inter-service communication must use mutual TLS (mTLS). Plaintext HTTP between services is strictly prohibited.",
     [("Design the service mesh configuration for the payment cluster.","mTLS","constraint_compliance"),
      ("What protocol must all inter-service communication use?","mutual TLS (mTLS)","exact_match"),
      ("Is plaintext HTTP allowed between services?","No","exact_match"),
      ("Create the network policy for the backend services.","mTLS required","constraint_compliance"),
      ("Design the certificate management strategy for microservices.","mTLS","constraint_compliance")]),
    ("PF-085",
     "DATA GOVERNANCE RULE: All data exported to external partners must pass through the DLP (Data Loss Prevention) gateway at dlp.corp.internal before transmission.",
     [("Design the partner data export pipeline.","DLP gateway dlp.corp.internal","constraint_compliance"),
      ("What gateway must all external data exports pass through?","dlp.corp.internal","exact_match"),
      ("What does DLP stand for?","Data Loss Prevention","exact_match"),
      ("Create the third-party API integration design.","DLP gateway","constraint_compliance"),
      ("Design the data export approval workflow.","DLP gateway at dlp.corp.internal","constraint_compliance")]),
    ("PF-086",
     "PERFORMANCE BASELINE: All database queries must complete in under 100 ms. Queries exceeding this must use indexed columns or be rewritten with pagination.",
     [("Design the search API database layer.","under 100 ms","constraint_compliance"),
      ("What is the maximum allowed query execution time?","100 ms","exact_match"),
      ("What two remedies apply for slow queries?","indexed columns or pagination","exact_match"),
      ("Create the reporting module database design.","100 ms limit","constraint_compliance"),
      ("Design the data export query strategy.","under 100 ms, indexed or paginated","constraint_compliance")]),
    ("PF-087",
     "AVAILABILITY REQUIREMENT: The system must implement circuit breakers for all downstream service calls with a failure threshold of 50% and a recovery window of 30 seconds.",
     [("Design the payment gateway integration.","circuit breaker","constraint_compliance"),
      ("What failure threshold triggers the circuit breaker?","50%","exact_match"),
      ("What is the circuit breaker recovery window?","30 seconds","exact_match"),
      ("Create the third-party API call strategy.","circuit breaker 50% failure","constraint_compliance"),
      ("Design the resilience pattern for downstream calls.","circuit breaker","constraint_compliance")]),
    ("PF-088",
     "CONTENT POLICY: All user-generated content must pass through the content moderation API at content-mod.internal before being published. No direct publishing.",
     [("Design the community post submission flow.","content moderation API","constraint_compliance"),
      ("What must happen before user content is published?","content moderation check","exact_match"),
      ("What is the moderation endpoint?","content-mod.internal","exact_match"),
      ("Create the comment publishing pipeline.","content-mod.internal","constraint_compliance"),
      ("Is direct publishing of user content allowed?","No","exact_match")]),
    ("PF-089",
     "BACKUP MANDATE: All database snapshots must be encrypted at rest using AES-256 and stored in a geo-redundant location.",
     [("Design the database backup strategy.","AES-256 geo-redundant","constraint_compliance"),
      ("What encryption standard must database backups use?","AES-256","exact_match"),
      ("What storage redundancy is required for backups?","geo-redundant","exact_match"),
      ("Create the disaster recovery plan for the database tier.","AES-256 encrypted geo-redundant","constraint_compliance"),
      ("Design the snapshot schedule and storage policy.","AES-256 geo-redundant","constraint_compliance")]),
    ("PF-090",
     "RATE LIMITING POLICY: All public API endpoints must enforce per-IP rate limiting of 100 requests per minute. Responses exceeding the limit must return HTTP 429.",
     [("Design the API gateway rate limiting configuration.","100 requests per minute per IP","constraint_compliance"),
      ("What HTTP status code is returned when the rate limit is exceeded?","429","exact_match"),
      ("What is the per-IP rate limit for public endpoints?","100 requests per minute","exact_match"),
      ("Create the rate limiting middleware specification.","100 RPM per IP, HTTP 429","constraint_compliance"),
      ("Design the abuse prevention layer for the API.","rate limiting 100 RPM per IP","constraint_compliance")]),
    ("PF-091",
     "OBSERVABILITY REQUIREMENT: Every service must expose a /metrics endpoint in Prometheus format for scraping by the central observability platform.",
     [("Design the monitoring integration for a new service.","Prometheus /metrics endpoint","constraint_compliance"),
      ("What endpoint must every service expose for metrics?","/metrics","exact_match"),
      ("In what format must metrics be exposed?","Prometheus format","exact_match"),
      ("Create the observability checklist for new service deployments.","Prometheus /metrics","constraint_compliance"),
      ("Design the metrics collection architecture.","Prometheus /metrics endpoint","constraint_compliance")]),
    ("PF-092",
     "DATA RESIDENCY RULE: All data from EU users must be stored and processed exclusively within EU-region infrastructure. Cross-region replication of EU data is prohibited.",
     [("Design the user data storage architecture for the EU market.","EU region only","constraint_compliance"),
      ("Where must EU user data be stored?","EU-region infrastructure","exact_match"),
      ("Is cross-region replication of EU data allowed?","No","exact_match"),
      ("Create the GDPR-compliant data routing policy.","EU data stays in EU region","constraint_compliance"),
      ("Design the multi-region deployment for the EU product.","EU-only storage for EU users","constraint_compliance")]),
    ("PF-093",
     "MANDATORY AUDIT TRAIL: Every change to a user's account permissions must be recorded in the audit log with: actor ID, target user ID, old value, new value, and timestamp.",
     [("Design the permission management service.","audit log with actor, target, old value, new value, timestamp","constraint_compliance"),
      ("What five fields must the permission audit log capture?","actor ID, target user ID, old value, new value, timestamp","exact_match"),
      ("Create the role change workflow.","audit trail with all five fields","constraint_compliance"),
      ("What must be logged when permissions change?","actor ID, target user ID, old value, new value, timestamp","exact_match"),
      ("Design the admin panel permission editor.","audit log required","constraint_compliance")]),
    ("PF-094",
     "FAILOVER REQUIREMENT: The primary database must automatically failover to the standby replica within 60 seconds of a primary failure, with no manual intervention.",
     [("Design the database high-availability architecture.","automatic failover within 60 seconds","constraint_compliance"),
      ("What is the maximum failover time?","60 seconds","exact_match"),
      ("Can failover require manual intervention?","No","exact_match"),
      ("Create the database resilience specification.","60-second automatic failover","constraint_compliance"),
      ("Design the recovery time objective for the database tier.","60 seconds automatic","constraint_compliance")]),
    ("PF-095",
     "API VERSIONING POLICY: New API versions must maintain backward compatibility for a minimum of 12 months after the successor version is released.",
     [("Design the API deprecation strategy.","12 months backward compatibility","constraint_compliance"),
      ("How long must backward compatibility be maintained?","12 months","exact_match"),
      ("From when does the 12-month backward compatibility clock start?","after the successor version is released","exact_match"),
      ("Create the API lifecycle management plan.","12-month compatibility window","constraint_compliance"),
      ("Design the versioning migration guide for API consumers.","12 months backward compatible","constraint_compliance")]),
    ("PF-096",
     "SECURITY SCANNING MANDATE: Every container image must pass a vulnerability scan with zero critical CVEs before being promoted to the production registry.",
     [("Design the CI/CD pipeline for container promotion.","vulnerability scan zero critical CVEs","constraint_compliance"),
      ("What CVE severity level must be zero before promotion?","critical","exact_match"),
      ("When must the vulnerability scan pass?","before promotion to the production registry","exact_match"),
      ("Create the container security gate specification.","zero critical CVEs","constraint_compliance"),
      ("Design the image promotion policy.","vulnerability scan zero critical CVEs","constraint_compliance")]),
    ("PF-097",
     "CACHING RULE: Cache invalidation events must be propagated to all nodes within 5 seconds. Stale reads beyond 5 seconds are a data integrity violation.",
     [("Design the distributed cache invalidation mechanism.","within 5 seconds","constraint_compliance"),
      ("What is the maximum cache invalidation propagation time?","5 seconds","exact_match"),
      ("What is a stale read beyond 5 seconds classified as?","data integrity violation","exact_match"),
      ("Create the cache consistency protocol.","5-second propagation","constraint_compliance"),
      ("Design the distributed session cache update strategy.","invalidation within 5 seconds","constraint_compliance")]),
    ("PF-098",
     "DEPENDENCY POLICY: No third-party library may be added to the codebase without a security review and approval from the AppSec team.",
     [("Design the dependency management workflow.","AppSec review and approval","constraint_compliance"),
      ("Who must approve new third-party libraries?","AppSec team","exact_match"),
      ("What process must precede adding a new library?","security review and approval from AppSec","exact_match"),
      ("Create the open-source intake process.","AppSec approval required","constraint_compliance"),
      ("Can a developer add a library without review?","No","exact_match")]),
    ("PF-099",
     "SCALABILITY POLICY: All services must implement graceful shutdown, completing in-flight requests within a 30-second drain window before terminating.",
     [("Design the Kubernetes pod lifecycle configuration.","30-second graceful shutdown","constraint_compliance"),
      ("What is the maximum drain window for graceful shutdown?","30 seconds","exact_match"),
      ("What must happen to in-flight requests during shutdown?","completed within 30 seconds","exact_match"),
      ("Create the deployment rollout strategy.","graceful shutdown 30 seconds","constraint_compliance"),
      ("Design the container termination lifecycle.","30-second drain window","constraint_compliance")]),
    ("PF-100",
     "NOTIFICATION REQUIREMENT: All system alerts of severity P1 or P2 must be sent via both email and SMS simultaneously. Using only one channel is non-compliant.",
     [("Design the alerting and notification pipeline.","email and SMS simultaneously for P1/P2","constraint_compliance"),
      ("Which two channels must be used for P1/P2 alerts?","email and SMS","exact_match"),
      ("Is it compliant to send a P1 alert only by email?","No","exact_match"),
      ("Create the on-call notification configuration.","P1/P2 via email and SMS","constraint_compliance"),
      ("Design the incident escalation notification design.","email and SMS for P1 and P2","constraint_compliance")]),
]


def build_fact(idx, data, fact_type):
    fact_id, statement, questions = data[0], data[1], data[2]
    qs = []
    for q in questions:
        qs.append({
            "q": q[0],
            "gold": q[1],
            "scoring": q[2],
            "keywords": q[3] if len(q) > 3 else [],
            "required_conclusion": q[4] if len(q) > 4 else "",
        })
    return {"id": fact_id, "type": fact_type, "statement": statement, "questions": qs}


probe_facts = []
for i, d in enumerate(EXPLICIT):
    probe_facts.append(build_fact(i, d, "explicit_recall"))
for i, d in enumerate(GROUNDED):
    probe_facts.append(build_fact(i, d, "grounded_reasoning"))
for i, d in enumerate(IMPLICIT):
    probe_facts.append(build_fact(i, d, "implicit_context"))

assert len(probe_facts) == 100, f"Expected 100 facts, got {len(probe_facts)}"
print(f"Generated {len(probe_facts)} probe facts")
print(f"  explicit_recall:  {sum(1 for f in probe_facts if f['type']=='explicit_recall')}")
print(f"  grounded_reasoning: {sum(1 for f in probe_facts if f['type']=='grounded_reasoning')}")
print(f"  implicit_context: {sum(1 for f in probe_facts if f['type']=='implicit_context')}")

OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open("w", encoding="utf-8") as f:
    json.dump({"probe_facts": probe_facts}, f, indent=2, ensure_ascii=False)
print(f"Written to {OUT}")
